<?php require 'partials/header.php';?>
    <section class="width-container">
        <h1>Scrap Tire Hauling</h1>
        <p>
            Tread Setters is licensed and Insured in the state of Virginia to haul and properly dispose of waste tires.
            Tread Setters is logistically managed to curbside pickup – tires on a weekly or bi weekly schedule
            depending on the volume generated by the generator or the request of you the generator. We currently
            offer these services in Northern Virginia, Richmond the Tri-Cities and all of the Hampton Roads area.
            Unlike our competitors we offer an outstanding program for the Original Generator please contact us
            for Validation and more information on this service.
        </p>
    </section>
<?php require 'partials/footer.php';?>